### ISSUE TITLE
Add default icon when api unable to fetch favicon

### ISSUE THREAD

**Issue by prajjwalkapoor** [prajjwalkapoor/kairy#2]
Currently, we are just dynamically creating URLs for the favicon. Instead of this, convert the getIcon function into the fetch call, and when API returns 404, display the default icon URL.
You can find this functions in `source/utils/getIcon.ts`

**Comment by aswinikalyan30** [comment]
Can i take this up?

**Comment by prajjwalkapoor** [comment]
@aswinikalyan30 You can now start working on this.

**Comment by Kitashi14** [comment]
would like to do this

**Comment by prajjwalkapoor** [comment]
@aswinikalyan30 any update on this?

**Comment by aswinikalyan30** [comment]
will raise PR today

**Comment by mittalvansh** [comment]
Can I take this?
