### ISSUE TITLE
Make onboarding screen

### ISSUE THREAD

**Issue by prajjwalkapoor** [prajjwalkapoor/kairy#3]
Make a guided onboarding experience for the user when they install the extension for the very first time.

For reference: 

![image](https://user-images.githubusercontent.com/68912239/195394430-ca9e680d-2fdf-44fa-af8e-423e71e8d643.png)
![image](https://user-images.githubusercontent.com/68912239/195394703-d21486aa-271e-4040-b01a-f7feac0fc464.png)

**Comment by Ananyamishra08** [comment]
Hello @prajjwalkapoor , can you assign me this issue?

**Comment by prajjwalkapoor** [comment]
@Ananyamishra08 You can now start working on this.

**Comment by prajjwalkapoor** [comment]
@Ananyamishra08 any update on this?

**Comment by Waishnav** [comment]
I would like to work on this issue. 
Do I need to create the onboarding screen's design in addition to working on it? Or
Do I have to apply the above design right away?

**Comment by prajjwalkapoor** [comment]
@Waishnav I have added the above design just for reference. Feel free to pivot the design accordingly. Also make sure that the onboarding screen is visible only after the first installation, not on every open.

**Comment by Waishnav** [comment]
Hey sorry for that I will not be able to work on this issue due to a busy schedule.
Can you unassign me??
