### ISSUE TITLE
Increase icon size of shortcuts in shortcut card

### ISSUE THREAD

**Issue by prajjwalkapoor** [prajjwalkapoor/kairy#7]
you can find shortcut card component in `source/Dashboard/components)/ShortcutCard/`

**Comment by vanshikaa-agarwal** [comment]
I want to work on this

**Comment by Aditya-Harsh** [comment]
Hi there,
I have experience working with components and would like to work on this issue.
Please assign it to me.

**Comment by prajjwalkapoor** [comment]
@Aditya-Harsh Thanks for showing interest in contributing to kairy.
This issue is already resolved but you can contribute to other open issues. see [issues](https://github.com/prajjwalkapoor/kairy/issues)
